### ISSUE TITLE
Android application crashes, when using SDK profile with Offline Access settings

### ISSUE THREAD

**Issue by tamasszadvari** [vmwareairwatchsdk/vmware-ws1-sdk-forms#3]
When I set the Offline Access setting in the SDK profile, with a MaximumPeriodAllowedOffline data at the UEM Console, the Android application crashes on start, with the following stacktrace:

09-18 14:34:39.309: E/AndroidRuntime(6961): android.runtime.JavaProxyThrowable: System.FormatException: Input string was not in a correct format.
09-18 14:34:39.309: E/AndroidRuntime(6961):   at System.Number.ThrowOverflowOrFormatException (System.Boolean overflow, System.String overflowResourceKey) [0x0001a] in <ea1e6881b2624701b35711c79b23a990>:0 
09-18 14:34:39.309: E/AndroidRuntime(6961):   at System.Number.ParseDouble (System.ReadOnlySpan\1[T] value, System.Globalization.NumberStyles styles, System.Globalization.NumberFormatInfo info) [0x0007d] in <ea1e6881b2624701b35711c79b23a990>:0 
09-18 14:34:39.309: E/AndroidRuntime(6961):   at System.Double.Parse (System.String s) [0x0001a] in <ea1e6881b2624701b35711c79b23a990>:0 
09-18 14:34:39.309: E/AndroidRuntime(6961):   at WorkspaceOne.Android.AWProfileMapper.getProfile () [0x003d3] in <77fd588a563d440582fb6fc0f6612ed1>:0 
09-18 14:34:39.309: E/AndroidRuntime(6961):   at WorkspaceOne.Android.WorkspaceOne.<OnPropertyChanged>b__17_0 () [0x0000b] in <77fd588a563d440582fb6fc0f6612ed1>:0 
09-18 14:34:39.309: E/AndroidRuntime(6961):   at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <ea1e6881b2624701b35711c79b23a990>:0 
09-18 14:34:39.309: E/AndroidRuntime(6961):   at System.Threading.Tasks.Task.Execute () [0x00000] in <ea1e6881b2624701b35711c79b23a990>:0 
09-18 14:34:39.309: E/AndroidRuntime(6961): --- End of stack trace from previous location where exception was thrown ---
09-18 14:34:39.309: E/AndroidRuntime(6961):   at WorkspaceOne.Android.WorkspaceOne.OnPropertyChanged (System.String propertyName) [0x00088] in <77fd588a563d440582fb6fc0f6612ed1>:0 
09-18 14:34:39.309: E/AndroidRuntime(6961):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <ea1e6881b2624701b35711c79b23a990>:0 
09-18 14:34:39.309: E/AndroidRuntime(6961):   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <8d5bcd572a4749c29ac25e716f542f56>:0 
09-18 14:34:39.309: E/AndroidRuntime(6961):   at Java.Lang.Thread+RunnableImplementor.Run () <0x7419174cd0 + 0x00067> in <8d5bcd572a4749c29ac25e716f542f56>:0 
09-18 14:34:39.309: E/AndroidRuntime(6961):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <8d5bcd572a4749c29ac25e716f542f56>:0 
09-18 14:34:39.309: E/AndroidRuntime(6961):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.99(intptr,intptr)
09-18 14:34:39.309: E/AndroidRuntime(6961): 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
09-18 14:34:39.309: E/AndroidRuntime(6961): 	at mono.java.lang.RunnableImplementor.run(SourceFile:30)
09-18 14:34:39.309: E/AndroidRuntime(6961): 	at android.os.Handler.handleCallback(Handler.java:808)
09-18 14:34:39.309: E/AndroidRuntime(6961): 	at android.os.Handler.dispatchMessage(Handler.java:101)
09-18 14:34:39.309: E/AndroidRuntime(6961): 	at android.os.Looper.loop(Looper.java:166)
09-18 14:34:39.309: E/AndroidRuntime(6961): 	at android.app.ActivityThread.main(ActivityThread.java:7425)
09-18 14:34:39.309: E/AndroidRuntime(6961): 	at java.lang.reflect.Method.invoke(Native Method)
09-18 14:34:39.309: E/AndroidRuntime(6961): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
09-18 14:34:39.309: E/AndroidRuntime(6961): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

I've found, that the `AWProfileMapper `class's `getProfile` method fails, when trying the parse the `MaximumPeriodAllowedOffline` property of the `OfflineAccess` setting, as a double.

If I disable the setting on the profile, it works fine. Also it's working fine on iOS.

**Comment by Maddy79** [comment]
@tamasszadvari , we will check and update you.

**Comment by Maddy79** [comment]
@tamasszadvari , anything on the above query?

**Comment by tamasszadvari** [comment]
@Maddy79 I'm sorry for the late response. The value has been set to 3 days.

**Comment by tamasszadvari** [comment]
@Maddy79 Any update on this issue?

**Comment by Maddy79** [comment]
@tamasszadvari , can you try with the latest forms package, we tried the time to be set to 3 days and were not seeing the crash.

**Comment by tamasszadvari** [comment]
@Maddy79 Unfortunately I couldn't make the app compile with the latest package. The compiler complains about missing resources (e.g.: style/Theme.MaterialComponents.DayNight.Bridge).
If I install the Xamarin.Google.Android.Material package, the app won' compile, because the minimum api level should be 28 at least.
So I'm stuck at this point.

**Comment by Maddy79** [comment]
@tamasszadvari , please use version 1.1.05 of the Xamarin.Google.Android.Material package.

**Comment by tamasszadvari** [comment]
@Maddy79 With that, the minSdk version has to bet 23 at least.

**Comment by Maddy79** [comment]
What is the min SDK version you can set for your app?

**Comment by tamasszadvari** [comment]
It was 21 before, because Android 5.0 is still has a big market share. Is it unavoidable to bump it up to 23?
